version: '3.8'

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
    command: go run cmd/statement-service/main.go -b 0.0.0.0
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./db/migrations/000002_create_report_table.up.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./db/migrations/000003_create_transaction_table.up.sql:/docker-entrypoint-initdb.d/2-init.sql
volumes:
    postgres-db: